"use strict";

const fs = require("fs");
const path = require("path");

const { defaultHealthCheck, regions } = require("../shared/regions");
const { strategyGroups, businessGroups } = require("../shared/groups");
const { rulesets, surgeRuleSetLocation } = require("../shared/rulesets");
const { inlineRulesBeforeRuleSets, registryAndLearningRules } = require("../shared/programmerRules");

const rootDir = path.resolve(__dirname, "..");

function ensureDir(relativeDir) {
  fs.mkdirSync(path.join(rootDir, relativeDir), { recursive: true });
}

function writeFile(relativePath, content) {
  const fullPath = path.join(rootDir, relativePath);
  ensureDir(path.dirname(relativePath));
  fs.writeFileSync(fullPath, `${content.trimEnd()}\n`, "utf8");
}

function uniq(items) {
  return [...new Set(items.filter(Boolean))];
}

function singleQuote(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function regionProxies() {
  return regions.map((region) => region.groupName);
}

/** Surge: shared snippet for external policy lists (subscription / node pool). */
function surgeExternalPolicyOpts(policyPath) {
  return `policy-path=${policyPath}, update-interval=86400`;
}

/**
 * Surge remote RULE-SET line. Uses extended-matching so DOMAIN rules in the set
 * also match TLS SNI / HTTP Host (see manual.nssurge.com/rule/ruleset).
 */
function surgeRuleSetLine(ruleset) {
  return `RULE-SET,${surgeRuleSetLocation(ruleset)},${ruleset.group},extended-matching`;
}

function renderOverwriteScript() {
  const payload = {
    defaultHealthCheck,
    regions,
    strategyGroups,
    businessGroups,
    rulesets,
    programmerInlineRules: inlineRulesBeforeRuleSets(),
  };

  return `// Generated by scripts/build.js
// Mihomo / Clash Party override entrypoint.
// Keep real subscription URLs outside this public repository.

const SHARED = ${JSON.stringify(payload, null, 2)};

function uniq(items) {
  return [...new Set((items || []).filter(Boolean))];
}

function escapeRegExp(pattern) {
  return new RegExp(pattern, "i");
}

function pickProxyNames(config) {
  return (config.proxies || []).map((proxy) => proxy && proxy.name).filter(Boolean);
}

function buildRegionGroups(allProxyNames) {
  return SHARED.regions.map((region) => {
    const matched = allProxyNames.filter((name) => escapeRegExp(region.match).test(name));
    return {
      name: region.groupName,
      type: "url-test",
      hidden: true,
      proxies: matched.length ? uniq(matched) : ["节点选择"],
      url: SHARED.defaultHealthCheck.url,
      interval: SHARED.defaultHealthCheck.interval,
      tolerance: SHARED.defaultHealthCheck.tolerance,
    };
  });
}

function buildStrategyGroups(allProxyNames) {
  return SHARED.strategyGroups.map((group) => {
    if (group.mode === "all-proxies") {
      return {
        name: group.name,
        type: group.type,
        proxies: uniq(allProxyNames),
        url: SHARED.defaultHealthCheck.url,
        interval: SHARED.defaultHealthCheck.interval,
        tolerance: SHARED.defaultHealthCheck.tolerance,
      };
    }

    return {
      name: group.name,
      type: group.type,
      proxies: uniq(group.proxies),
    };
  });
}

function buildBusinessGroups() {
  return SHARED.businessGroups.map((group) => ({
    name: group.name,
    type: group.type,
    proxies: uniq(group.proxies),
  }));
}

function buildRuleProviders() {
  return SHARED.rulesets.reduce((providers, ruleset) => {
    providers[ruleset.key] = {
      type: "http",
      behavior: ruleset.behavior,
      url: ruleset.mihomoUrl,
      path: ruleset.mihomoPath,
      interval: 86400,
    };
    return providers;
  }, {});
}

function buildRules() {
  return [
    ...(SHARED.programmerInlineRules || []),
    ...SHARED.rulesets.map((ruleset) => \`RULE-SET,\${ruleset.key},\${ruleset.group}\`),
    "MATCH,漏网之鱼",
  ];
}

const main = (config) => {
  config.proxies ??= [];
  config["proxy-groups"] ??= [];
  config["rule-providers"] ??= {};
  config.rules ??= [];

  const allProxyNames = pickProxyNames(config);
  const groups = [
    ...buildStrategyGroups(allProxyNames),
    ...buildRegionGroups(allProxyNames),
    ...buildBusinessGroups(),
  ];

  config["proxy-groups"] = groups;
  config["rule-providers"] = buildRuleProviders();
  config.rules = buildRules();

  return config;
};
`;
}

function renderMihomoYaml(subscriptionUrl) {
  const lines = [
    "# Generated by scripts/build.js",
    subscriptionUrl === "__MIHOMO_SUBSCRIPTION_URL__"
      ? "# Public template for Clash Mi / Mihomo clients."
      : "# Private example template for Clash Mi / Mihomo clients.",
    "# Replace the placeholder subscription URL only in a local private copy.",
    "# Subscription response: airports usually return a body that is Base64 text; decoded lines are share links (ss/vmess/trojan/vless/anytls/…).",
    "# Mihomo type:http proxy-providers fetch that URL and parse standard subscription formats automatically — no extra Base64 decoder option is required.",
    "",
    "mixed-port: 7890",
    "allow-lan: false",
    "mode: rule",
    "log-level: info",
    "ipv6: true",
    "",
    "proxy-providers:",
    "  airport:",
    "    type: http",
    `    url: ${singleQuote(subscriptionUrl)}`,
    "    path: ./providers/airport.yaml",
    "    interval: 86400",
    "    health-check:",
    "      enable: true",
    `      url: ${singleQuote(defaultHealthCheck.url)}`,
    `      interval: ${defaultHealthCheck.interval}`,
    "",
    "proxy-groups:",
  ];

  for (const group of strategyGroups) {
    if (group.mode === "all-proxies") {
      lines.push(`  - name: ${singleQuote(group.name)}
    type: ${group.type}
    use:
      - airport
    url: ${singleQuote(defaultHealthCheck.url)}
    interval: ${defaultHealthCheck.interval}
    tolerance: ${defaultHealthCheck.tolerance}`);
    } else {
      const proxies = uniq(group.proxies).map((p) => `      - ${singleQuote(p)}`).join("\n");
      lines.push(`  - name: ${singleQuote(group.name)}
    type: ${group.type}
    proxies:\n${proxies}`);
    }
  }

  for (const region of regions) {
    lines.push(`  - name: ${singleQuote(region.groupName)}
    type: url-test
    hidden: true
    use:
      - airport
    filter: ${singleQuote(`(?i)(${region.match})`)}
    url: ${singleQuote(defaultHealthCheck.url)}
    interval: ${defaultHealthCheck.interval}
    tolerance: ${defaultHealthCheck.tolerance}`);
  }

  for (const group of businessGroups) {
    const proxies = uniq(group.proxies).map((p) => `      - ${singleQuote(p)}`).join("\n");
    lines.push(`  - name: ${singleQuote(group.name)}
    type: ${group.type}
    proxies:\n${proxies}`);
  }

  lines.push("");
  lines.push("rule-providers:");
  for (const ruleset of rulesets) {
    lines.push(`  ${ruleset.key}:
    type: http
    behavior: ${ruleset.behavior}
    url: ${singleQuote(ruleset.mihomoUrl)}
    path: ${singleQuote(ruleset.mihomoPath)}
    interval: 86400`);
  }

  lines.push("");
  lines.push("rules:");
  for (const ruleLine of inlineRulesBeforeRuleSets()) {
    lines.push(`  - ${singleQuote(ruleLine)}`);
  }
  for (const ruleset of rulesets) {
    lines.push(`  - ${singleQuote(`RULE-SET,${ruleset.key},${ruleset.group}`)}`);
  }
  lines.push(`  - ${singleQuote("MATCH,漏网之鱼")}`);

  return lines.join("\n");
}

function renderSurgeConf() {
  return renderSurgeConfWithPath("__SURGE_POLICY_PATH__");
}

function surgeGeneralAndHostLines() {
  const hcUrl = defaultHealthCheck.url;
  return [
    "[General]",
    "# Align connectivity checks with url-test groups; tune test-timeout if probes are flaky on slow networks.",
    `proxy-test-url = ${hcUrl}`,
    "test-timeout = 5",
    "internet-test-url = http://captive.apple.com/hotspot-detect.html",
    "show-error-page-for-reject = true",
    "# RFC1918 + CGNAT + link-local IPv6 + Bonjour-style hosts (matches built-in RULE-SET,LAN coverage).",
    "skip-proxy = 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 100.64.0.0/10, fe80::/10, localhost, *.local",
    "ipv6 = true",
    "loglevel = notify",
    "# Route by rule (not only by domain list): enables PROCESS-NAME / finer control in optional includes.",
    "enhanced-mode-by-rule = true",
    "# Optional REST API for scripts / Shortcuts (set a strong token; never expose to LAN). Uncomment to use:",
    "# external-controller = 127.0.0.1:6170",
    "# external-controller-access = surge@REPLACE_WITH_SECRET",
    "",
    "[Host]",
    "# Map hackable hostnames to localhost (examples — uncomment and duplicate as needed):",
    "# myapp.test = 127.0.0.1",
    "# api.local = 127.0.0.1",
    "",
  ];
}

/** Shared header comments for single-file Surge templates (monolithic public / private). */
function surgeMonolithicPreambleLines(policyPath) {
  return [
    "# Generated by scripts/build.js",
    policyPath === "__SURGE_POLICY_PATH__"
      ? "# Public template for Surge (macOS / iOS; policy-path works the same)."
      : "# Private example template for Surge (macOS / iOS).",
    "# The public repo should only keep placeholders. Put real subscription conversion endpoints in a private copy.",
    "# Surge policy-path must point to a Surge policy list (plain policy lines), NOT the same Base64 subscription URL as Mihomo.",
    "# If your airport only exposes Base64 subscribe links, use a private subconverter (or similar) that outputs Surge format, then put that URL/path here.",
    "# policy-path relative paths (./foo.txt) resolve from this profile file's directory in Surge — prefer an absolute path if you import from another folder.",
    "# No [Proxy] section: every url-test group loads nodes from the same policy-path below (avoids a duplicate external line that could fail on wrong ./ resolution).",
    "",
  ];
}

/** [Proxy Group] through end of [Rule] (and trailing optional-include comments). */
function surgeProxyGroupAndRuleLines(policyPath) {
  const allRegions = regionProxies();
  const extPolicy = surgeExternalPolicyOpts(policyPath);
  const hcUrl = defaultHealthCheck.url;
  const hcInterval = defaultHealthCheck.interval;
  const hcTolerance = defaultHealthCheck.tolerance;
  const lines = [
    "[Proxy Group]",
    "# Surge Mac 5.7+ / iOS 5.11+: smart auto-select; older cores ignore first line and use url-test.",
    `#!REQUIREMENT CORE_VERSION>=22 自动选择 = smart, ${extPolicy}, url=${hcUrl}, interval=${hcInterval}, tolerance=${hcTolerance}`,
    `自动选择 = url-test, ${extPolicy}, url=${hcUrl}, interval=${hcInterval}, tolerance=${hcTolerance}, timeout=5 //!REQUIREMENT CORE_VERSION<22`,
    `节点选择 = select, 自动选择, ${allRegions.join(", ")}, DIRECT`,
  ];

  for (const region of regions) {
    lines.push(
      `${region.groupName} = url-test, ${extPolicy}, policy-regex-filter=${singleQuote(region.match)}, url=${hcUrl}, interval=${hcInterval}, tolerance=${hcTolerance}, timeout=5`
    );
  }

  for (const group of businessGroups) {
    lines.push(`${group.name} = select, ${uniq(group.proxies).join(", ")}`);
  }

  lines.push("");
  lines.push("[Rule]");
  lines.push("# Built-in ruleset: no download, matches RFC1918 / .local / IPv6 link-local (see manual RULE-SET,LAN).");
  lines.push("RULE-SET,LAN,DIRECT");
  lines.push(
    "# Localhost + registries + learning sites — edit shared/programmerRules.js and run node scripts/build.js to change."
  );
  for (const ruleLine of registryAndLearningRules()) {
    lines.push(ruleLine);
  }
  lines.push("# Remote rulesets: extended-matching applies DOMAIN rules to SNI and HTTP Host when applicable.");
  for (const ruleset of rulesets) {
    lines.push(surgeRuleSetLine(ruleset));
  }
  lines.push("FINAL,漏网之鱼");
  lines.push("");
  lines.push("# Optional: add PROCESS-NAME / extra DOMAIN rules in a file beside this profile, then uncomment:");
  lines.push("# #!include surge-local-overrides.conf");
  lines.push("# See surge/surge-local-overrides.example.conf in the repo.");

  return lines;
}

function renderSurgeConfWithPath(policyPath) {
  return [
    ...surgeMonolithicPreambleLines(policyPath),
    ...surgeGeneralAndHostLines(),
    ...surgeProxyGroupAndRuleLines(policyPath),
  ].join("\n");
}

function main() {
  const mihomoPrivateUrl = process.env.MIHOMO_SUBSCRIPTION_URL;
  const surgePrivatePolicyPath = process.env.SURGE_POLICY_PATH;
  const overwriteScript = renderOverwriteScript();
  writeFile("mihomo/overwrite.js", overwriteScript);
  writeFile("mihomo/mihomo-public.yaml", renderMihomoYaml("__MIHOMO_SUBSCRIPTION_URL__"));
  writeFile(
    "mihomo/mihomo-private.example.yaml",
    renderMihomoYaml("https://example.com/your-private-airport-subscription")
  );
  if (mihomoPrivateUrl) {
    writeFile("mihomo/mihomo-private.yaml", renderMihomoYaml(mihomoPrivateUrl));
  }
  writeFile("surge/surge-public.conf", renderSurgeConf());
  writeFile(
    "surge/surge-private.example.conf",
    renderSurgeConfWithPath("https://example.com/your-private-surge-policy.list")
  );
  if (surgePrivatePolicyPath) {
    writeFile("surge/surge-private.conf", renderSurgeConfWithPath(surgePrivatePolicyPath));
  }
}

main();
