"use strict";

const fs = require("fs");
const path = require("path");

const { defaultHealthCheck, regions } = require("../shared/regions");
const { strategyGroups, businessGroups } = require("../shared/groups");
const { rulesets } = require("../shared/rulesets");

const rootDir = path.resolve(__dirname, "..");

function ensureDir(relativeDir) {
  fs.mkdirSync(path.join(rootDir, relativeDir), { recursive: true });
}

function writeFile(relativePath, content) {
  const fullPath = path.join(rootDir, relativePath);
  ensureDir(path.dirname(relativePath));
  fs.writeFileSync(fullPath, `${content.trimEnd()}\n`, "utf8");
}

function uniq(items) {
  return [...new Set(items.filter(Boolean))];
}

function singleQuote(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function regionProxies() {
  return regions.map((region) => region.groupName);
}

function renderOverwriteScript() {
  const payload = {
    defaultHealthCheck,
    regions,
    strategyGroups,
    businessGroups,
    rulesets,
  };

  return `// Generated by scripts/build.js
// Mihomo / Clash Party override entrypoint.
// Keep real subscription URLs outside this public repository.

const SHARED = ${JSON.stringify(payload, null, 2)};

function uniq(items) {
  return [...new Set((items || []).filter(Boolean))];
}

function escapeRegExp(pattern) {
  return new RegExp(pattern, "i");
}

function pickProxyNames(config) {
  return (config.proxies || []).map((proxy) => proxy && proxy.name).filter(Boolean);
}

function buildRegionGroups(allProxyNames) {
  return SHARED.regions.map((region) => {
    const matched = allProxyNames.filter((name) => escapeRegExp(region.match).test(name));
    return {
      name: region.groupName,
      type: "url-test",
      proxies: matched.length ? uniq(matched) : ["节点选择"],
      url: SHARED.defaultHealthCheck.url,
      interval: SHARED.defaultHealthCheck.interval,
      tolerance: SHARED.defaultHealthCheck.tolerance,
    };
  });
}

function buildStrategyGroups(allProxyNames) {
  return SHARED.strategyGroups.map((group) => {
    if (group.mode === "all-proxies") {
      return {
        name: group.name,
        type: group.type,
        proxies: uniq(allProxyNames),
        url: SHARED.defaultHealthCheck.url,
        interval: SHARED.defaultHealthCheck.interval,
        tolerance: SHARED.defaultHealthCheck.tolerance,
      };
    }

    return {
      name: group.name,
      type: group.type,
      proxies: uniq(group.proxies),
    };
  });
}

function buildBusinessGroups() {
  return SHARED.businessGroups.map((group) => ({
    name: group.name,
    type: group.type,
    proxies: uniq(group.proxies),
  }));
}

function buildRuleProviders() {
  return SHARED.rulesets.reduce((providers, ruleset) => {
    providers[ruleset.key] = {
      type: "http",
      behavior: ruleset.behavior,
      url: ruleset.mihomoUrl,
      path: ruleset.mihomoPath,
      interval: 86400,
    };
    return providers;
  }, {});
}

function buildRules() {
  const ordered = SHARED.rulesets.map((ruleset) => \`RULE-SET,\${ruleset.key},\${ruleset.group}\`);
  ordered.push("MATCH,漏网之鱼");
  return ordered;
}

const main = (config) => {
  config.proxies ??= [];
  config["proxy-groups"] ??= [];
  config["rule-providers"] ??= {};
  config.rules ??= [];

  const allProxyNames = pickProxyNames(config);
  const groups = [
    ...buildStrategyGroups(allProxyNames),
    ...buildRegionGroups(allProxyNames),
    ...buildBusinessGroups(),
  ];

  config["proxy-groups"] = groups;
  config["rule-providers"] = buildRuleProviders();
  config.rules = buildRules();

  return config;
};
`;
}

function renderMihomoYaml(subscriptionUrl) {
  const lines = [
    "# Generated by scripts/build.js",
    subscriptionUrl === "__MIHOMO_SUBSCRIPTION_URL__"
      ? "# Public template for Clash Mi / Mihomo clients."
      : "# Private example template for Clash Mi / Mihomo clients.",
    "# Replace the placeholder subscription URL only in a local private copy.",
    "# The provider URL is expected to be the raw subscription endpoint whose body is a base64-encoded AnyTLS node list.",
    "",
    "mixed-port: 7890",
    "allow-lan: false",
    "mode: rule",
    "log-level: info",
    "ipv6: true",
    "",
    "proxy-providers:",
    "  airport:",
    "    type: http",
    `    url: ${singleQuote(subscriptionUrl)}`,
    "    path: ./providers/airport.yaml",
    "    interval: 86400",
    "    health-check:",
    "      enable: true",
    `      url: ${singleQuote(defaultHealthCheck.url)}`,
    `      interval: ${defaultHealthCheck.interval}`,
    "",
    "proxy-groups:",
  ];

  for (const group of strategyGroups) {
    lines.push(`  - name: ${singleQuote(group.name)}`);
    lines.push(`    type: ${group.type}`);
    if (group.mode === "all-proxies") {
      lines.push("    use:");
      lines.push("      - airport");
      lines.push(`    url: ${singleQuote(defaultHealthCheck.url)}`);
      lines.push(`    interval: ${defaultHealthCheck.interval}`);
      lines.push(`    tolerance: ${defaultHealthCheck.tolerance}`);
    } else {
      lines.push("    proxies:");
      for (const proxy of uniq(group.proxies)) {
        lines.push(`      - ${singleQuote(proxy)}`);
      }
    }
  }

  for (const region of regions) {
    lines.push(`  - name: ${singleQuote(region.groupName)}`);
    lines.push("    type: url-test");
    lines.push("    use:");
    lines.push("      - airport");
    lines.push(`    filter: ${singleQuote(`(?i)(${region.match})`)}`);
    lines.push(`    url: ${singleQuote(defaultHealthCheck.url)}`);
    lines.push(`    interval: ${defaultHealthCheck.interval}`);
    lines.push(`    tolerance: ${defaultHealthCheck.tolerance}`);
  }

  for (const group of businessGroups) {
    lines.push(`  - name: ${singleQuote(group.name)}`);
    lines.push(`    type: ${group.type}`);
    lines.push("    proxies:");
    for (const proxy of uniq(group.proxies)) {
      lines.push(`      - ${singleQuote(proxy)}`);
    }
  }

  lines.push("");
  lines.push("rule-providers:");
  for (const ruleset of rulesets) {
    lines.push(`  ${ruleset.key}:`);
    lines.push("    type: http");
    lines.push(`    behavior: ${ruleset.behavior}`);
    lines.push(`    url: ${singleQuote(ruleset.mihomoUrl)}`);
    lines.push(`    path: ${singleQuote(ruleset.mihomoPath)}`);
    lines.push("    interval: 86400");
  }

  lines.push("");
  lines.push("rules:");
  for (const ruleset of rulesets) {
    lines.push(`  - ${singleQuote(`RULE-SET,${ruleset.key},${ruleset.group}`)}`);
  }
  lines.push(`  - ${singleQuote("MATCH,漏网之鱼")}`);

  return lines.join("\n");
}

function renderSurgeConf() {
  return renderSurgeConfWithPath("__SURGE_POLICY_PATH__");
}

function renderSurgeConfWithPath(policyPath) {
  const allRegions = regionProxies();
  const lines = [
    "# Generated by scripts/build.js",
    policyPath === "__SURGE_POLICY_PATH__"
      ? "# Public template for Surge (macOS)."
      : "# Private example template for Surge (macOS).",
    "# The public repo should only keep placeholders. Put real subscription conversion endpoints in a private copy.",
    "# A raw base64 AnyTLS airport subscription should be converted privately into a Surge-consumable policy list.",
    "",
    "[General]",
    "skip-proxy = 127.0.0.1, localhost, *.local",
    "ipv6 = true",
    "loglevel = notify",
    "",
    "[Proxy]",
    "# Fill this in privately with your converted AnyTLS/Surge policy list URL or local file.",
    `机场订阅 = external, policy-path=${policyPath}, update-interval=86400`,
    "",
    "[Proxy Group]",
    `自动选择 = url-test, policy-path=${policyPath}, update-interval=86400, url=${defaultHealthCheck.url}, interval=${defaultHealthCheck.interval}, tolerance=${defaultHealthCheck.tolerance}`,
    `节点选择 = select, 自动选择, ${allRegions.join(", ")}, DIRECT`,
  ];

  for (const region of regions) {
    lines.push(
      `${region.groupName} = url-test, policy-path=${policyPath}, update-interval=86400, policy-regex-filter=${singleQuote(region.match)}, url=${defaultHealthCheck.url}, interval=${defaultHealthCheck.interval}, tolerance=${defaultHealthCheck.tolerance}`
    );
  }

  for (const group of businessGroups) {
    lines.push(`${group.name} = select, ${uniq(group.proxies).join(", ")}`);
  }

  lines.push("");
  lines.push("[Rule]");
  for (const ruleset of rulesets) {
    lines.push(`RULE-SET,${ruleset.surgeUrl},${ruleset.group}`);
  }
  lines.push("FINAL,漏网之鱼");

  return lines.join("\n");
}

function main() {
  const mihomoPrivateUrl = process.env.MIHOMO_SUBSCRIPTION_URL;
  const surgePrivatePolicyPath = process.env.SURGE_POLICY_PATH;
  const overwriteScript = renderOverwriteScript();
  writeFile("mihomo/overwrite.js", overwriteScript);
  writeFile("scripts/overwrite.js", overwriteScript);
  writeFile("overwrite.js", overwriteScript);
  writeFile("mihomo/mihomo-public.yaml", renderMihomoYaml("__MIHOMO_SUBSCRIPTION_URL__"));
  writeFile(
    "mihomo/mihomo-private.example.yaml",
    renderMihomoYaml("https://example.com/your-private-airport-subscription")
  );
  if (mihomoPrivateUrl) {
    writeFile("mihomo/mihomo-private.yaml", renderMihomoYaml(mihomoPrivateUrl));
  }
  writeFile("surge/surge-public.conf", renderSurgeConf());
  writeFile(
    "surge/surge-private.example.conf",
    renderSurgeConfWithPath("https://example.com/your-private-surge-policy.list")
  );
  if (surgePrivatePolicyPath) {
    writeFile("surge/surge-private.conf", renderSurgeConfWithPath(surgePrivatePolicyPath));
  }
}

main();
