// Generated by scripts/build.js
// Mihomo / Clash Party override entrypoint.
// Keep real subscription URLs outside this public repository.

const SHARED = {
  "defaultHealthCheck": {
    "url": "https://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  "regions": [
    {
      "key": "hong_kong",
      "name": "香港",
      "groupName": "香港节点",
      "match": "香港|HK|Hong\\s*Kong"
    },
    {
      "key": "taiwan",
      "name": "台湾",
      "groupName": "台湾节点",
      "match": "台湾|TW|Taiwan|Taipei"
    },
    {
      "key": "japan",
      "name": "日本",
      "groupName": "日本节点",
      "match": "日本|JP|Japan|Tokyo|Osaka"
    },
    {
      "key": "singapore",
      "name": "新加坡",
      "groupName": "新加坡节点",
      "match": "新加坡|狮城|SG|Singapore"
    },
    {
      "key": "united_states",
      "name": "美国",
      "groupName": "美国节点",
      "match": "美国|US|USA|United\\s*States|America|Los\\s*Angeles|San\\s*Jose|Seattle"
    },
    {
      "key": "united_kingdom",
      "name": "英国",
      "groupName": "英国节点",
      "match": "英国|UK|United\\s*Kingdom|Britain|England|London|Manchester"
    },
    {
      "key": "australia",
      "name": "澳洲",
      "groupName": "澳洲节点",
      "match": "澳洲|澳大利亚|AU|Australia|Sydney|Melbourne|Perth"
    },
    {
      "key": "malaysia",
      "name": "马来西亚",
      "groupName": "马来西亚节点",
      "match": "马来西亚|MY|Malaysia|Kuala\\s*Lumpur"
    },
    {
      "key": "argentina",
      "name": "阿根廷",
      "groupName": "阿根廷节点",
      "match": "阿根廷|AR|Argentina|Buenos\\s*Aires"
    }
  ],
  "strategyGroups": [
    {
      "key": "auto",
      "name": "自动选择",
      "type": "url-test",
      "mode": "all-proxies"
    },
    {
      "key": "select",
      "name": "节点选择",
      "type": "select",
      "proxies": [
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点",
        "DIRECT"
      ]
    }
  ],
  "businessGroups": [
    {
      "name": "国外媒体",
      "type": "select",
      "proxies": [
        "节点选择",
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点"
      ]
    },
    {
      "name": "AI平台",
      "type": "select",
      "proxies": [
        "节点选择",
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点"
      ]
    },
    {
      "name": "开发工具与镜像",
      "type": "select",
      "proxies": [
        "节点选择",
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点",
        "DIRECT"
      ]
    },
    {
      "name": "学习与研究",
      "type": "select",
      "proxies": [
        "节点选择",
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点",
        "DIRECT"
      ]
    },
    {
      "name": "即时通讯",
      "type": "select",
      "proxies": [
        "节点选择",
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点"
      ]
    },
    {
      "name": "微软服务",
      "type": "select",
      "proxies": [
        "节点选择",
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点",
        "DIRECT"
      ]
    },
    {
      "name": "苹果服务",
      "type": "select",
      "proxies": [
        "DIRECT",
        "节点选择",
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点"
      ]
    },
    {
      "name": "游戏平台",
      "type": "select",
      "proxies": [
        "节点选择",
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点"
      ]
    },
    {
      "name": "国外网站",
      "type": "select",
      "proxies": [
        "节点选择",
        "自动选择",
        "香港节点",
        "台湾节点",
        "日本节点",
        "新加坡节点",
        "美国节点",
        "英国节点",
        "澳洲节点",
        "马来西亚节点",
        "阿根廷节点"
      ]
    },
    {
      "name": "国内网站",
      "type": "select",
      "proxies": [
        "DIRECT",
        "节点选择"
      ]
    },
    {
      "name": "广告拦截",
      "type": "select",
      "proxies": [
        "REJECT",
        "DIRECT"
      ]
    },
    {
      "name": "漏网之鱼",
      "type": "select",
      "proxies": [
        "节点选择",
        "自动选择",
        "DIRECT"
      ]
    }
  ],
  "rulesets": [
    {
      "key": "advertising",
      "sourceName": "Advertising",
      "group": "广告拦截",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml",
      "mihomoPath": "./ruleset/Advertising.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list"
    },
    {
      "key": "openai",
      "sourceName": "OpenAI",
      "group": "AI平台",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml",
      "mihomoPath": "./ruleset/OpenAI.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list"
    },
    {
      "key": "claude",
      "sourceName": "Claude",
      "group": "AI平台",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml",
      "mihomoPath": "./ruleset/Claude.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Claude/Claude.list"
    },
    {
      "key": "anthropic",
      "sourceName": "Anthropic",
      "group": "AI平台",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Anthropic/Anthropic.yaml",
      "mihomoPath": "./ruleset/Anthropic.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Anthropic/Anthropic.list"
    },
    {
      "key": "gemini",
      "sourceName": "Gemini",
      "group": "AI平台",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml",
      "mihomoPath": "./ruleset/Gemini.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Gemini/Gemini.list"
    },
    {
      "key": "copilot",
      "sourceName": "Copilot",
      "group": "AI平台",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml",
      "mihomoPath": "./ruleset/Copilot.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Copilot/Copilot.list"
    },
    {
      "key": "cursor",
      "sourceName": "Cursor",
      "group": "AI平台",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/YOUR_GITHUB_USER/Rules/master/mihomo/ruleset/Cursor.yaml",
      "mihomoPath": "./ruleset/Cursor.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/YOUR_GITHUB_USER/Rules/master/mihomo/ruleset/Cursor.list"
    },
    {
      "key": "youtube",
      "sourceName": "YouTube",
      "group": "国外媒体",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml",
      "mihomoPath": "./ruleset/YouTube.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list"
    },
    {
      "key": "netflix",
      "sourceName": "Netflix",
      "group": "国外媒体",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml",
      "mihomoPath": "./ruleset/Netflix.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Netflix/Netflix.list"
    },
    {
      "key": "spotify",
      "sourceName": "Spotify",
      "group": "国外媒体",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml",
      "mihomoPath": "./ruleset/Spotify.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Spotify/Spotify.list"
    },
    {
      "key": "tiktok",
      "sourceName": "TikTok",
      "group": "国外媒体",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml",
      "mihomoPath": "./ruleset/TikTok.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/TikTok/TikTok.list"
    },
    {
      "key": "globalmedia",
      "sourceName": "GlobalMedia",
      "group": "国外媒体",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml",
      "mihomoPath": "./ruleset/GlobalMedia.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GlobalMedia/GlobalMedia.list"
    },
    {
      "key": "github",
      "sourceName": "GitHub",
      "group": "AI平台",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml",
      "mihomoPath": "./ruleset/GitHub.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GitHub/GitHub.list"
    },
    {
      "key": "npmjs",
      "sourceName": "Npmjs",
      "group": "开发工具与镜像",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Npmjs/Npmjs.yaml",
      "mihomoPath": "./ruleset/Npmjs.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Npmjs/Npmjs.list"
    },
    {
      "key": "docker",
      "sourceName": "Docker",
      "group": "开发工具与镜像",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Docker/Docker.yaml",
      "mihomoPath": "./ruleset/Docker.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Docker/Docker.list"
    },
    {
      "key": "python",
      "sourceName": "Python",
      "group": "开发工具与镜像",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Python/Python.yaml",
      "mihomoPath": "./ruleset/Python.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Python/Python.list"
    },
    {
      "key": "gitlab",
      "sourceName": "GitLab",
      "group": "开发工具与镜像",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitLab/GitLab.yaml",
      "mihomoPath": "./ruleset/GitLab.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GitLab/GitLab.list"
    },
    {
      "key": "scholar",
      "sourceName": "Scholar",
      "group": "学习与研究",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Scholar/Scholar.yaml",
      "mihomoPath": "./ruleset/Scholar.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Scholar/Scholar.list"
    },
    {
      "key": "wikipedia",
      "sourceName": "Wikipedia",
      "group": "学习与研究",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Wikipedia/Wikipedia.yaml",
      "mihomoPath": "./ruleset/Wikipedia.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Wikipedia/Wikipedia.list"
    },
    {
      "key": "stackexchange",
      "sourceName": "Stackexchange",
      "group": "学习与研究",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Stackexchange/Stackexchange.yaml",
      "mihomoPath": "./ruleset/Stackexchange.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Stackexchange/Stackexchange.list"
    },
    {
      "key": "google",
      "sourceName": "Google",
      "group": "国外网站",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml",
      "mihomoPath": "./ruleset/Google.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list"
    },
    {
      "key": "telegram",
      "sourceName": "Telegram",
      "group": "即时通讯",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml",
      "mihomoPath": "./ruleset/Telegram.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Telegram/Telegram.list"
    },
    {
      "key": "discord",
      "sourceName": "Discord",
      "group": "即时通讯",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.yaml",
      "mihomoPath": "./ruleset/Discord.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Discord/Discord.list"
    },
    {
      "key": "twitter",
      "sourceName": "Twitter",
      "group": "国外网站",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml",
      "mihomoPath": "./ruleset/Twitter.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitter/Twitter.list"
    },
    {
      "key": "microsoft",
      "sourceName": "Microsoft",
      "group": "微软服务",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml",
      "mihomoPath": "./ruleset/Microsoft.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list"
    },
    {
      "key": "apple",
      "sourceName": "Apple",
      "group": "苹果服务",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml",
      "mihomoPath": "./ruleset/Apple.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list"
    },
    {
      "key": "steam",
      "sourceName": "Steam",
      "group": "游戏平台",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml",
      "mihomoPath": "./ruleset/Steam.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Steam/Steam.list"
    },
    {
      "key": "epic",
      "sourceName": "Epic",
      "group": "游戏平台",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml",
      "mihomoPath": "./ruleset/Epic.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Epic/Epic.list"
    },
    {
      "key": "lan",
      "sourceName": "Lan",
      "group": "国内网站",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml",
      "mihomoPath": "./ruleset/Lan.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan.list"
    },
    {
      "key": "chinamedia",
      "sourceName": "ChinaMedia",
      "group": "国内网站",
      "behavior": "classical",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml",
      "mihomoPath": "./ruleset/ChinaMedia.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaMedia/ChinaMedia.list"
    },
    {
      "key": "china",
      "sourceName": "ChinaMax",
      "mihomoFile": "ChinaMax_Domain",
      "group": "国内网站",
      "behavior": "domain",
      "mihomoUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml",
      "mihomoPath": "./ruleset/ChinaMax_Domain.yaml",
      "surgeUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaMax/ChinaMax.list"
    }
  ],
  "programmerInlineRules": [
    "DOMAIN,localhost,DIRECT",
    "IP-CIDR,127.0.0.0/8,DIRECT,no-resolve",
    "IP-CIDR6,::1/128,DIRECT,no-resolve"
  ]
};

function uniq(items) {
  return [...new Set((items || []).filter(Boolean))];
}

function escapeRegExp(pattern) {
  return new RegExp(pattern, "i");
}

function pickProxyNames(config) {
  return (config.proxies || []).map((proxy) => proxy && proxy.name).filter(Boolean);
}

function buildRegionGroups(allProxyNames) {
  return SHARED.regions.map((region) => {
    const matched = allProxyNames.filter((name) => escapeRegExp(region.match).test(name));
    return {
      name: region.groupName,
      type: "url-test",
      hidden: true,
      proxies: matched.length ? uniq(matched) : ["节点选择"],
      url: SHARED.defaultHealthCheck.url,
      interval: SHARED.defaultHealthCheck.interval,
      tolerance: SHARED.defaultHealthCheck.tolerance,
    };
  });
}

function buildStrategyGroups(allProxyNames) {
  return SHARED.strategyGroups.map((group) => {
    if (group.mode === "all-proxies") {
      return {
        name: group.name,
        type: group.type,
        proxies: uniq(allProxyNames),
        url: SHARED.defaultHealthCheck.url,
        interval: SHARED.defaultHealthCheck.interval,
        tolerance: SHARED.defaultHealthCheck.tolerance,
      };
    }

    return {
      name: group.name,
      type: group.type,
      proxies: uniq(group.proxies),
    };
  });
}

function buildBusinessGroups() {
  return SHARED.businessGroups.map((group) => ({
    name: group.name,
    type: group.type,
    proxies: uniq(group.proxies),
  }));
}

function buildRuleProviders() {
  return SHARED.rulesets.reduce((providers, ruleset) => {
    providers[ruleset.key] = {
      type: "http",
      behavior: ruleset.behavior,
      url: ruleset.mihomoUrl,
      path: ruleset.mihomoPath,
      interval: 86400,
    };
    return providers;
  }, {});
}

function buildRules() {
  return [
    ...(SHARED.programmerInlineRules || []),
    ...SHARED.rulesets.map((ruleset) => `RULE-SET,${ruleset.key},${ruleset.group}`),
    "MATCH,漏网之鱼",
  ];
}

const main = (config) => {
  config.proxies ??= [];
  config["proxy-groups"] ??= [];
  config["rule-providers"] ??= {};
  config.rules ??= [];

  const allProxyNames = pickProxyNames(config);
  const groups = [
    ...buildStrategyGroups(allProxyNames),
    ...buildRegionGroups(allProxyNames),
    ...buildBusinessGroups(),
  ];

  config["proxy-groups"] = groups;
  config["rule-providers"] = buildRuleProviders();
  config.rules = buildRules();

  return config;
};
